development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  host: "localhost"
  pool: 5
  username: username
  password: "userpassword"

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  host: "localhost"
  pool: 5
  username: username
  password: "userpassword"