prodaction:
  adapter: postgresql
  encoding: unicode
  database: news_portal_prodaction
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"

development:
  adapter: postgresql
  encoding: unicode
  database: news_portal_development
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"

test:
  adapter: postgresql
  encoding: unicode
  database: news_portal_test
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"
